name: Pipeline-complete
#change the event
on:
  push:
    branches: [ feature ]
# env:
#   APPLICATION_NAME: startupapp

jobs:
  login_AWS:
    runs-on: [ ubuntu-latest ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # see: https://github.com/aws-actions/configure-aws-credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
  submit_processing_job:
    needs: [ login_AWS ]
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    outputs:
      output1: ${{ steps.sm_process.outputs.outputt }}
    steps:
    - uses: actions/checkout@v2
    - name: Fire SageMaker
      id: sm_process
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        PREFIX: ${{ secrets.PREFIX }}
        IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        echo "details are important file" >> details.txt
        pip install --no-cache-dir --upgrade awscli pandas boto3 sagemaker sklearn argparse numpy fsspec s3fs tabulate
        python preprocecssing-script-demo.py
        #echo "::set-output name=outputt::$(cat details.txt)"
        #cat details.txt
    - name: upload details artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact-proc-to-train
        path: details.txt
  
  submit_training_job:
    needs: [submit_processing_job]
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    
    steps:
    - name: download details artifacts
      uses: actions/download-artifact@v3
      with:
        name: artifact-proc-to-train
    - name : output-step
      id : outputstep
#       run: echo "::set-output name=outputt::$(cat details.txt)"
      run: echo "test=$(cat details.txt)" >> $GITHUB_OUTPUT

    - uses : actions/checkout@v2
    - name : Fire SageMaker
#       id : sm_train
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        PREFIX: ${{ secrets.PREFIX }}
        IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        pip install --no-cache-dir --upgrade awscli pandas boto3 sagemaker sklearn argparse numpy fsspec s3fs tabulate
        echo ${{needs.submit_processing_job.outputs.output1}} >> details.txt
        python training-script-demo.py 
